name: Normal Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello
        env:
          SERVICE_ACCOUNT: ${{ secrets.API_KEY }}
          CREDENTIALS_JSON: ${{ secrets.AWS_SERVICE_ACCOUNT_CREDS }}
        run: |
          echo "Successfully used credentials to deploy application."
