name: Normal Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello
        with:
          service_account: ${{secrets.API_KEY}}
          credentials_json: ${{secrets.AWS_SERVICE_ACCOUNT_CREDS}}
        run: echo "Succesfully used credentials to deploy application."

